language: bash
git:
  depth: false
os: linux
dist: xenial
env:
  - JDK="bellsoft-jdk8u265+1-linux-amd64-full"
stages:
  - check
  - telegram
jobs:
  include:
    - stage: check
      name: "Gradle check on Linux OS and JDK8"
      os: linux
      before_script:
        - echo "Downloading jdk"
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - source ./install-jdk.sh --url https://download.bell-sw.com/java/8u265+1/bellsoft-jdk8u265+1-linux-amd64-full.tar.gz
        - java -version
      script:
        - ./gradlew clean build fatjar --parallel
    - stage: telegram
      name: Telegram notification
      if: tag IS NOT present AND type != pull_request
      os: linux
      script:
        - 'curl -X  POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID
      -d "text=$(dirname $TRAVIS_REPO_SLUG) pushed to $TRAVIS_BRANCH %0ACommit: $TRAVIS_COMMIT_MESSAGE%0ALink:
      https://github.com/Unibo-PPS-1920/pps-19-motoScala/commits/$TRAVIS_BRANCH"'
before_deploy:
  - echo "Preparing for deploy"
  - mkdir -p report
  - cp --parent */build/reports build/reports report -R
deploy:
  - provider: releases
    api_key:
      secure: Q/1LXFY3iRS5HhAdt8oL9f6DFIwiZ2zBKfI0Yh8kFq0r7IntdGGBdlhAdy+Uxch60MdmS3HfgqducR4ZuBMzYe9gHd2N5xDj9K9Y0BDoN4vE7Y6MCUEjeRXDg40eDlNpaFnHwAc7RIU8jVwBQ3C+QSilwBSjoa8eEXCSu7Q76KyvgtvkP9ietjN9cOsXFPkGgcCaPRAc4naGNZ5Y2uChpTVtIRHZgafXRul8MUiHJritUSgixymr9ARgW0T0Q8wjz5LP6gYkLOFBm34VvQO38pb0rcufva4KMW9CkF/zexkwVTknjZL8OKWSmnhls5DKPn+yvNSg8SmKvN3DOFTdoncExqgcIJYqWOd/4iUP2JTvyEzOZtr93v87fb/SxzRjx/OgrRNOHL4tpMRsBZdQVnSQO7uNvqCWhGmO6hFRzWib5sEZgfl/xg4u6ZMuba8ARrFME9DZkpbwwQz6BORvZjvfoXhsmCOxF4o7eNYikgLvc87jOPsI7KgjHGJxuwzO9eZ5ER2ziBwfg/j0q4zeZ4qEmhyaSL6lCxhLFvkj91DOb7Q9erC/bax05z1J89Q8CHp8TcpDLUbxK13kN/lWmNOx04dqCTQ3Y0Ke0dsZlaGJLna9DlIipLoYs586XILF14lOaJFRI3UGDtlzLnDfH8P+GE3ji02v9szccFXUNaw=
    file_glob: true
    file: "${HOME}/build/Unibo-PPS-1920/pps-19-motoScala/build/libs/pps-19-motoScala-*.jar"
    on:
      os: linux
      repo: Unibo-PPS-1920/pps-19-motoScala
      branch: release
      tags: true
    skip_cleanup: 'true'
  - provider: pages
    github_token: $GITHUB_TOKEN
    edge: true # opt in to dpl v2
    on:
      branch: release
    local_dir: "${HOME}/build/Unibo-PPS-1920/pps-19-motoScala/report"
after_deploy: 'curl -X  POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage
  -d chat_id=$TELEGRAM_CHAT_ID -d "text= Commit: $TRAVIS_COMMIT_MESSAGE %0ATag: $TRAVIS_TAG
  %0ALink: https://github.com/Unibo-PPS-1920/pps-19-motoScala/releases/latest/download/"'
