language: bash
git:
  depth: false
os: linux
dist: xenial
env:
  - JDK="bellsoft-jdk8u265+1-linux-amd64-full"
stages:
  - check
jobs:
  include:
    - stage: check
      name: "Gradle check on Linux OS and JDK 8"
      os: linux
      before_script:
        - echo "Downloading jdk"
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - source ./install-jdk.sh --url https://download.bell-sw.com/java/8u265+1/bellsoft-jdk8u265+1-linux-amd64-full.tar.gz
        - java -version
      script:
        - ./gradlew check --scan --parallel
before_deploy:
  - echo "Preparing for deploy"
  - ./gradlew assemble scaladoc --scan --parallel
  - mkdir -p report
  - cp --parent */build/reports build/reports report -R
  - cp --parent */build/docs build/docs report -R
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "${HOME}/build/Unibo-PPS-1920/pps-19-motoScala/build/libs/pps-19-motoScala-*.jar"
    skip_cleanup: 'true'
    on:
      os: linux
      repo: Unibo-PPS-1920/pps-19-motoScala
      branch: release
      tags: true
  - provider: pages
    github_token: $GITHUB_TOKEN
    edge: true
    skip_cleanup: 'true'
    local_dir: "${HOME}/build/Unibo-PPS-1920/pps-19-motoScala/report"
    on:
      os: linux
      repo: Unibo-PPS-1920/pps-19-motoScala
      branch: release
      tags: true

